# Command+a prefix instead of default Command+b
set  -g prefix C-a
setw -g mode-keys vi

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Gruvbox
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'light256' # Options: 'dark', 'dark256', 'light', 'light256'
set -g @plugin 'tmux-plugins/tmux-resurrect'

bind a send-prefix
bind-key C-a last-window
bind-key -n C-k send-keys -R Enter \; clear-history
bind-key h   select-pane -L
bind-key j   select-pane -D
bind-key k   select-pane -U
bind-key l   select-pane -R
bind-key |   split-window -h
bind-key c   choose-session

# M-Up and M-Down are bound by default but explicitly binding here in case that
# ever changes. If M-Left and M-Right don't work, the terminal might be setting
# Option to Alt in MacOS. Configure your terminal to not do any special
# handling of Option key on MacOS
bind-key -r    M-Up resize-pane -U 5
bind-key -r  M-Down resize-pane -D 5
bind-key -r  M-Left resize-pane -L 5
bind-key -r M-Right resize-pane -R 5

# Clear the screen and history
bind C-l run-shell "for i in {1..10}; do tmux send-keys -t ! Enter; done; tmux clear-history -t !"

# allows scrolling and selecting in copy-mode
set -g mouse on

# start window numbering at 1
set -g base-index 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

